server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql驱动包
    url: jdbc:mysql://www.samphanie.cn:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
    username: sam
    password: Zxx131013@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.samphanie.springcloud.entities  # 所有Entity别名类所在包

eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka  # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版

  instance:
    instance-id: payment8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # Eureka 客户端向服务器发送心跳的时间间隔，单位为秒（默认为30s）
    # lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最好一次心跳后等待时间上限，单位为秒（默认为90s），超时将剔除服务
    # lease-expiration-duration-in-seconds: 2

