server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:      # 此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:   # 表示定义的名称，用于binding整合
          type: rabbit   # 消息组件类型
          environment:   # 设置rabbitmq的环境配置
            spring:
              rabbitmq:
                host: www.samphanie.cn
                port: 5672
                username: admin
                password: Zxx131013@
                virtual-host: /
      bindings:  # 服务的整合处理
        input:  # 这个名字是一个通道的名称
          destination:  studyExchange     # 表示要使用的EXchange名称定义
          content-type: application/json  # 设置消息类型，本次为json,文本则设置为“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: samB

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5         # 设置心跳的时间间隔（默认30秒）
#    lease-expiration-duration-in-seconds: 30         #如果超过30s的间隔 ，服务将被踢出
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
