server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true       # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh                  # 路由的ID， 没有固定的规则，但要求唯一，配合服务名称
#          uri: http://localhost:8001         # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**           # 断言
            #- After=2020-04-23T23:30:39.201+08:00[Asia/Shanghai]
            - Cookie=username,zxx

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    hostname: cloud-gateway-service