server:
  port: 8004

spring:
  application:
    name: zookeeper-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql驱动包
    url: jdbc:mysql://www.samphanie.cn:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
    username: sam
    password: Zxx131013@

  cloud:
    zookeeper:
      connect-string: www.samphanie.cn:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.samphanie.springcloud.entities  # 所有Entity别名类所在包
