server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
    instance-id: feignhystrixorder80
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        # 指的是建立连接后从服务器读取到可用资源所用的时间
        connectTimeout: 3000
        # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
        readTimeout: 3000